// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgvrtiewienicehnlyno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNndnJ0aWV3aWVuaWNlaG5seW5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMDUxNjYsImV4cCI6MjA3MzU4MTE2Nn0.1M5JnWRRdDLoY5XeJVGzrFepsZAS_cFeWw1BMr6pHcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});